Repository dialpad/dialtone, pull requests merged in 2020-10, with the labels that each got.

#124 Modals
  docs/.eleventy.js
  docs/_data/modals.json
  docs/_data/nav.json
  docs/_includes/nav.html
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/js/modals.js
  docs/assets/less/dialtone-docs.less
  docs/components/buttons/circle-buttons.html
  docs/components/buttons/icons.html
  docs/components/buttons/sizes.html
  docs/components/modals.html
  docs/components/toast.html
  docs/icons/brand.html
  docs/icons/sizes.html
  docs/icons/system.html
  lib/build/less/components/modals.less
  lib/build/less/dialtone-classes.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: enhancement

#123 Margin & Padding Utility Classes
  docs/_data/spacing.json
  docs/_data/type.json
  docs/_includes/nav.html
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/images/favicons/apple-touch-icon-1024x1024--local.png
  docs/assets/images/favicons/apple-touch-icon-1024x1024--staging.png
  docs/assets/images/favicons/apple-touch-icon-1024x1024.png
  docs/assets/images/spacing-example.png
  docs/assets/js/modals.js
  docs/components/buttons/circle-buttons.html
  docs/components/buttons/icons.html
  docs/components/buttons/inverted.html
  docs/components/buttons/loading.html
  docs/components/buttons/sizes.html
  docs/components/links.html
  docs/components/modals.html
  docs/components/tables.html
  docs/components/toast.html
  docs/components/tooltips.html
  docs/getting-started/usage.html
  docs/icons/sizes.html
  docs/utilities/layout/display.html
  docs/utilities/layout/flex/align-justify.html
  docs/utilities/layout/flex/center.html
  docs/utilities/layout/flex/columns.html
  docs/utilities/layout/flex/flex-classes.html
  docs/utilities/layout/flex/order.html
  docs/utilities/layout/grid/nesting-grids.html
  docs/utilities/layout/height.html
  docs/utilities/layout/margin.html
  docs/utilities/layout/overflow.html
  docs/utilities/layout/padding.html
  docs/utilities/layout/positioning.html
  docs/utilities/layout/stacks.html
  docs/utilities/layout/width.html
  docs/utilities/typography/colors.html
  docs/utilities/typography/font-family.html
  docs/utilities/typography/font-weight.html
  docs/utilities/typography/layout.html
  docs/utilities/typography/line-height.html
  docs/utilities/typography/sizes.html
  docs/utilities/typography/styles.html
  docs/utilities/typography/text-opacity.html
  docs/utilities/visual/backgrounds.html
  docs/utilities/visual/border-colors.html
  docs/utilities/visual/box-shadows.html
  docs/variables/spacing.html
  lib/build/less/utilities/margin.less
  lib/build/less/utilities/padding.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: enhancement

#129 Remove extra close icon from danger modal example
  docs/components/modals.html
Labels: bug

#128 Include a note not to include links or info private to Dialpad employees
  .github/pull_request_template.md
Labels: documentation
