Repository dialpad/dialtone, pull requests merged in 2021-04, with the labels that each got.

#263 Cleaned up Avatars documentation.
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/avatars.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/avatars.html
Labels: v6

#264 Removing SVG fill utility class and documentation
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/site-nav.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/utilities/svg/fill.html
  lib/less/utilities/colors.less
Labels: v6

#267 V6 component badge
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/badges.json
  docs/_data/nav.json
  docs/_data/site-nav.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/badges.html
  lib/less/components/badges.less
  lib/less/dialtone.less
Labels: v6

#268 V6 component avatar
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/avatars.json
  docs/_data/nav.json
  docs/_data/site-nav.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/images/person.png
  docs/components/avatars.html
  lib/less/components/avatars.less
  lib/less/dialtone.less
Labels: v6

#269 Dialtone V6 Component Table Implementation
  docs/components/tables.html
  lib/less/components/tables.less
Labels: v6

#265 Dialtone V6 Component Toast Implementation
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/banners.json
  docs/_data/toasts.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/js/toasts.js
  docs/components/toasts.html
  lib/less/components/banners.less
  lib/less/components/notices.less
  lib/less/components/toast.less
Labels: v6

#272 V6 component tables docs
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/tables.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/tables.html
  lib/less/components/tables.less
Labels: documentation

#273 Misc docs cleanup
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/type.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/banners.html
  docs/components/tooltips.html
  docs/utilities/interactivity/cursor.html
  docs/utilities/layout/overflow.html
  docs/utilities/layout/visibility.html
  docs/utilities/responsive/breakpoints.html
  docs/utilities/typography/font-family.html
  lib/less/utilities/layout.less
  lib/less/utilities/responsive.less
Labels: documentation, v6

#278 Added d-link--disabled and d-link--inverted--disabled
  docs/assets/css/dialtone--syntax.css
  docs/assets/css/dialtone--syntax.min.css
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/links.html
  lib/build/less/components/links.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: bug

#279 Adds inverted disabled link style
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/links.html
  lib/less/components/links.less
Labels: v6

#276 V6 component toast docs
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/toasts.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/js/toasts.js
  docs/components/toasts.html
  lib/less/components/toast.less
Labels: documentation, v6

#281 V6 component tables
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/tables.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/tables.html
  lib/less/components/tables.less
Labels: v6

#282 V6 component toast
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/banners.json
  docs/_data/toasts.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/js/toasts.js
  docs/components/toasts.html
  lib/less/components/banners.less
  lib/less/components/notices.less
  lib/less/components/toast.less
Labels: v6

#284 Fixed scrollSpy bug. It wasn't being destroyed properly.
  dist/css/dialtone.min.css
  docs/assets/css/dialtone.min.css
  docs/assets/js/nav.js
Labels: bug, v6

#274 Dialtone V6 Component Modal Implementation
  docs/components/modals.html
  lib/less/components/modals.less
Labels: v6

#285 V6 component modal docs
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/modal.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/modal.html
Labels: documentation, v6

#286 Fixing up color documentation.
  docs/_data/colors.json
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/less/dialtone-docs.less
  docs/design/colors.html
Labels: documentation, v6

#290 Cleaned up spacing documentation.
  docs/design/spacing.html
Labels: documentation

#289 Clean up Adding icon and favicon documentation
  docs/_data/site-nav.json
  docs/design/icons/adding.html
  docs/design/icons/favicons.html
Labels: documentation

#287 V6 component button css
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/button.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/buttons/circle-buttons.html
  lib/less/components/button.less
Labels: v6

#293 V6 Component: Inputs documentation
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/inputs.json
  docs/_data/site-nav.json
  docs/_data/textareas.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/forms.html
  docs/components/inputs.html
  docs/components/textarea.html
  lib/less/components/inputs.less
Labels: documentation, v6

#295 Design documentation icons
  docs/.eleventy.js
  docs/_data/site-nav.json
  docs/_includes/layouts/page-icons.html
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/less/dialtone-docs.less
  docs/design/colors/color-palette.html
  docs/design/icons/brand.html
  docs/design/icons/sizes.html
  docs/design/icons/system.html
  docs/design/icons/weather.html
  docs/design/illustrations/patterns.html
  docs/design/spacing/spacing-system.html
  docs/design/typography.html
Labels: documentation, v6

#299 V6 component button docs
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/button.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/button.html
  lib/less/components/button.less
Labels: documentation, v6

#298 Adds release instructions
  .github/RELEASING.md
  package-lock.json
  package.json
Labels: documentation

#300 V6 Component Modal
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/modal.json
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/modal.html
  lib/less/components/modal.less
Labels: v6

#302 Updated Select documentation.
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/select.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/select.html
Labels: documentation, v6

#303 Illustrations: Pattern documentation clean-up
  docs/design/icons/weather.html
  docs/design/illustrations/patterns.html
Labels: documentation, v6
