Repository dialpad/dialtone, pull requests merged in 2021-08, with the labels that each got.

#384 Fix hero image size bug in Safari
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/less/dialtone-docs.less
  docs/index.html
Labels: bug, documentation, v6

#386 Adds raise hand system icon and more CC brand icons to DT6
  docs/_data/svg-brand.json
  docs/_data/svg-system.json
  docs/_includes/icons/brand/diners-club.svg
  docs/_includes/icons/brand/discover.svg
  docs/_includes/icons/brand/jcb.svg
  docs/_includes/icons/brand/maestro.svg
  docs/_includes/icons/brand/union-pay.svg
  docs/_includes/icons/system/raise-hand.svg
  lib/build/svg/brand/diners-club.svg
  lib/build/svg/brand/discover.svg
  lib/build/svg/brand/jcb.svg
  lib/build/svg/brand/maestro.svg
  lib/build/svg/brand/union-pay.svg
  lib/build/svg/system/raise-hand.svg
  lib/dist/svg/brand/diners-club.svg
  lib/dist/svg/brand/discover.svg
  lib/dist/svg/brand/jcb.svg
  lib/dist/svg/brand/maestro.svg
  lib/dist/svg/brand/union-pay.svg
  lib/dist/svg/system/raise-hand.svg
  lib/dist/vue/icons/IconDinersClub.vue
  lib/dist/vue/icons/IconDiscover.vue
  lib/dist/vue/icons/IconJcb.vue
  lib/dist/vue/icons/IconMaestro.vue
  lib/dist/vue/icons/IconRaiseHand.vue
  lib/dist/vue/icons/IconUnionPay.vue
Labels: icon, v6

#385 Added raise hand system icon and five more CC brand icons.
  docs/_data/svg-brand.json
  docs/_data/svg-system.json
  docs/_includes/icons/brand/diners-club.svg
  docs/_includes/icons/brand/discover.svg
  docs/_includes/icons/brand/jcb.svg
  docs/_includes/icons/brand/maestro.svg
  docs/_includes/icons/brand/union-pay.svg
  docs/_includes/icons/system/raise-hand.svg
  lib/build/svg/brand/diners-club.svg
  lib/build/svg/brand/discover.svg
  lib/build/svg/brand/jcb.svg
  lib/build/svg/brand/maestro.svg
  lib/build/svg/brand/union-pay.svg
  lib/build/svg/system/raise-hand.svg
  lib/dist/svg/brand/diners-club.svg
  lib/dist/svg/brand/discover.svg
  lib/dist/svg/brand/jcb.svg
  lib/dist/svg/brand/maestro.svg
  lib/dist/svg/brand/union-pay.svg
  lib/dist/svg/system/raise-hand.svg
  lib/dist/vue/icons/IconDinersClub.vue
  lib/dist/vue/icons/IconDiscover.vue
  lib/dist/vue/icons/IconJcb.vue
  lib/dist/vue/icons/IconMaestro.vue
  lib/dist/vue/icons/IconRaiseHand.vue
  lib/dist/vue/icons/IconUnionPay.vue
Labels: icon

#391 Re add list group
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  lib/build/less/components/list-group.less
  lib/build/less/dialtone.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: v6

#392 V6 add version
  .github/RELEASING.md
  docs/_includes/version.html
  docs/index.html
  gulpfile.js
Labels: documentation, v6

#404 Update outdated spacing system documentation
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/design/spacing/spacing-system.html
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: documentation, v6

#414 Adding select Archivo fonts and weights to support marketing copy.
  docs/_data/type.json
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/fonts/Archivo-Bold.woff2
  docs/assets/fonts/Archivo-Regular.woff2
  docs/assets/fonts/Archivo-SemiBold.woff2
  docs/assets/fonts/ArchivoExpanded-SemiBold.woff2
  docs/assets/fonts/ArchivoSemiExpanded-Medium.woff2
  docs/assets/fonts/ArchivoSemiExpanded-SemiBold.woff2
  docs/utilities/typography/font-family.html
  docs/utilities/typography/font-weight.html
  lib/build/less/utilities/typography.less
  lib/build/less/variables/typography.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
  lib/dist/fonts/Archivo-Bold.woff2
  lib/dist/fonts/Archivo-Regular.woff2
  lib/dist/fonts/Archivo-SemiBold.woff2
  lib/dist/fonts/ArchivoExpanded-SemiBold.woff2
  lib/dist/fonts/ArchivoSemiExpanded-Medium.woff2
  lib/dist/fonts/ArchivoSemiExpanded-SemiBold.woff2
Labels: v6

#416 Added Archivo fonts
  docs/_data/type.json
  docs/assets/css/dialtone--syntax.css
  docs/assets/css/dialtone--syntax.min.css
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/fonts/.DS_Store
  docs/assets/fonts/Archivo/Archivo-Bold.woff2
  docs/assets/fonts/Archivo/Archivo-Regular.woff2
  docs/assets/fonts/Archivo/Archivo-SemiBold.woff2
  docs/assets/fonts/Archivo/ArchivoExpanded-SemiBold.woff2
  docs/assets/fonts/Archivo/ArchivoSemiExpanded-Medium.woff2
  docs/assets/fonts/Archivo/ArchivoSemiExpanded-SemiBold.woff2
  lib/build/less/utilities/typography.less
  lib/build/less/variables/typography.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: enhancement

#420 DT-99 Update Select: Fix arrow icons position
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  lib/build/less/components/selects.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: bug, v6
