Repository dialpad/dialtone, pull requests merged in 2021-12, with the labels that each got.

#508 docs: add "Making a Pull Request" section to docs
  .github/CONTRIBUTING.md
Labels: documentation

#474 feat: add responsive variations
  dialtone.less
  docs/.eleventy.js
  docs/_includes/mobile-header.html
  docs/assets/js/mobile-header.js
  docs/assets/js/nav.js
  docs/assets/less/dialtone-docs.less
  docs/components/banner.html
  docs/components/modal.html
  docs/components/table.html
  docs/components/toast.html
  docs/utilities/borders/radius.html
  docs/utilities/effects/transition.html
  docs/utilities/flex/columns-layouts.html
  docs/utilities/flex/flex-grow-shrink.html
  docs/utilities/grid/layouts.html
  docs/utilities/layout/coordinates.html
  docs/utilities/layout/display.html
  docs/utilities/responsive/breakpoints.html
  docs/utilities/sizing/min-width.html
  docs/utilities/spacing/auto-spacing.html
  docs/utilities/typography/text-align.html
  docs/utilities/typography/whitespace.html
  docs/utilities/typography/word-break.html
  gulpfile.js
  lib/build/less/components/banner.less
  lib/build/less/components/button.less
  lib/build/less/components/forms.less
  lib/build/less/components/input.less
  lib/build/less/components/modal.less
  lib/build/less/components/notice.less
  lib/build/less/components/selects.less
  lib/build/less/components/table.less
  lib/build/less/components/toast.less
  lib/build/less/dialtone.less
  lib/build/less/themes/default.less
  lib/build/less/utilities/backgrounds.less
  lib/build/less/utilities/borders.less
  lib/build/less/utilities/colors.less
  lib/build/less/utilities/effects.less
  lib/build/less/utilities/flex.less
  lib/build/less/utilities/grid.less
  lib/build/less/utilities/internals.less
  lib/build/less/utilities/layout.less
  lib/build/less/utilities/responsive.less
  lib/build/less/utilities/sizing.less
  lib/build/less/utilities/spacing.less
  lib/build/less/utilities/svg.less
  lib/build/less/utilities/typography.less
  lib/build/less/variables/layout.less
  package-lock.json
  package.json
  postcss.config.js
Labels: enhancement

#510 docs: add coding guidelines to CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#509 docs: dt-120 Component a11y update
  docs/_data/banner.json
  docs/_data/breadcrumbs.json
  docs/_data/modal.json
  docs/_data/notice.json
  docs/_data/tabs.json
  docs/_data/toast.json
  docs/_data/tooltip.json
  docs/components/avatar.html
  docs/components/badge.html
  docs/components/banner.html
  docs/components/breadcrumbs.html
  docs/components/button.html
  docs/components/checkbox.html
  docs/components/input.html
  docs/components/link.html
  docs/components/modal.html
  docs/components/notice.html
  docs/components/radio.html
  docs/components/select.html
  docs/components/tabs.html
  docs/components/toast.html
  docs/components/tooltip.html
Labels: documentation

#512 feat: add foundational a11y documentation
  docs/_data/site-nav.json
  docs/assets/images/accessibility-graphic.png
  docs/getting-started/accessibility/best-practices.html
  docs/getting-started/accessibility/fundamentals.html
  docs/getting-started/accessibility/tooling.html
  docs/getting-started/best-practices.html
Labels: documentation, a11y

#517 feat: add windows logo as system icon
  docs/_data/svg-system.json
  lib/build/svg/system/windows.svg
Labels: icons
