Repository dialpad/dialtone, pull requests merged in 2021-05, with the labels that each got.

#304 V6 components select
  dist/css/dialtone.min.css
  docs/_data/select.json
  docs/_data/site-nav.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/banner.html
  docs/components/select.html
  docs/components/toast.html
  lib/build/less/components/forms.less
  lib/build/less/components/selects.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: v6

#309 Re-factored muted buttons
  docs/_data/button.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/button.html
  lib/build/less/components/button.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: v6

#315 Fixed broken Modal button
  docs/assets/js/modal.js
  docs/components/modal.html
  lib/build/less/components/modal.less
Labels: v6

#317 Removed link component's padding.
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  lib/build/less/components/link.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: v6

#318 Hide dark mode mentions for now
  docs/_includes/header.html
  docs/utilities/backgrounds/color.html
  docs/utilities/backgrounds/gradients.html
  docs/utilities/borders/color.html
  docs/utilities/typography/color.html
Labels: v6

#323 Adding missing d-notice__message class description
  docs/_data/notice.json
Labels: v6

#324 Link polish
  docs/_data/link.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/button.html
  docs/components/buttons/brand.html
  docs/components/buttons/circle-buttons.html
  docs/components/buttons/danger.html
  docs/components/buttons/icons.html
  docs/components/buttons/inverted.html
  docs/components/buttons/loading.html
  docs/components/buttons/muted.html
  docs/components/buttons/primary.html
  docs/components/buttons/sizes.html
  docs/components/link.html
  lib/build/less/components/link.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: documentation, v6

#325 Added a voice chat icon svg to be used with voice channels.
  docs/_data/svg-system.json
  docs/_includes/icons/system/voice-chat.svg
  lib/build/svg/system/voice-chat.svg
  lib/dist/svg/system/voice-chat.svg
  lib/dist/vue/icons/IconVoiceChat.vue
  package-lock.json
  package.json
Labels: icon

#334 Color clean-up
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/link.html
  docs/utilities/borders/color.html
  lib/build/less/components/avatar.less
  lib/build/less/themes/default.less
  lib/build/less/utilities/backgrounds.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: bug, v6

#337 Updated banner, notice, and toast base icon from transcript to lightb…
  docs/components/banner.html
  docs/components/notice.html
  docs/components/toast.html
Labels: v6

#338 Validation message polish
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/checkbox.html
  docs/components/input.html
  docs/components/radio.html
  lib/build/less/components/forms.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: v6

#339 Alphabetical order for avatar, badge, and link classes and examples
  docs/_data/avatar.json
  docs/_data/badge.json
  docs/_data/link.json
  docs/components/badge.html
  docs/components/link.html
Labels: v6

#326 Added Amex, Mastercard, and Visa brand logos.
  docs/_data/svg-brand.json
  docs/_includes/icons/brand/amex.svg
  docs/_includes/icons/brand/mastercard.svg
  docs/_includes/icons/brand/visa.svg
  lib/build/svg/brand/amex.svg
  lib/build/svg/brand/mastercard.svg
  lib/build/svg/brand/visa.svg
  lib/dist/svg/brand/amex.svg
  lib/dist/svg/brand/mastercard.svg
  lib/dist/svg/brand/visa.svg
  lib/dist/vue/icons/IconAmex.vue
  lib/dist/vue/icons/IconMastercard.vue
  lib/dist/vue/icons/IconVisa.vue
Labels: icon

#340 Added Amex, Mastercard, and Visa brand icons from DT5
  docs/_data/svg-brand.json
  docs/_includes/icons/brand/amex.svg
  docs/_includes/icons/brand/mastercard.svg
  docs/_includes/icons/brand/visa.svg
  lib/build/svg/brand/amex.svg
  lib/build/svg/brand/mastercard.svg
  lib/build/svg/brand/visa.svg
  lib/dist/svg/brand/amex.svg
  lib/dist/svg/brand/mastercard.svg
  lib/dist/svg/brand/visa.svg
  lib/dist/vue/icons/IconAmex.vue
  lib/dist/vue/icons/IconMastercard.vue
  lib/dist/vue/icons/IconVisa.vue
Labels: icon, v6
