Repository dialpad/dialtone, pull requests merged in 2021-09, with the labels that each got.

#423 Patches issue with Archivo integration
  .gitignore
  docs/assets/css/dialtone-docs.css
  docs/assets/css/dialtone-docs.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/fonts/Archivo-Bold.woff2
  docs/assets/fonts/Archivo-Regular.woff2
  docs/assets/fonts/Archivo-SemiBold.woff2
  docs/assets/fonts/ArchivoExpanded-SemiBold.woff2
  docs/assets/fonts/ArchivoSemiExpanded-Medium.woff2
  docs/assets/fonts/ArchivoSemiExpanded-SemiBold.woff2
  docs/assets/fonts/MarkWeb-Bold.woff
  docs/assets/fonts/MarkWeb-BoldItalic.woff
  docs/assets/fonts/MarkWeb-ExtraLight.woff
  docs/assets/fonts/MarkWeb-Italic.woff
  docs/assets/fonts/MarkWeb-Light.woff
  docs/assets/fonts/MarkWeb-LightItalic.woff
  docs/assets/fonts/MarkWeb-Medium.woff
  docs/assets/fonts/MarkWeb-MediumItalic.woff
  docs/assets/fonts/MarkWeb.woff
  docs/assets/less/dialtone-docs.less
  lib/build/fonts/Archivo-Bold.woff2
  lib/build/fonts/Archivo-Regular.woff2
  lib/build/fonts/Archivo-SemiBold.woff2
  lib/build/fonts/ArchivoExpanded-SemiBold.woff2
  lib/build/fonts/ArchivoSemiExpanded-Medium.woff2
  lib/build/fonts/ArchivoSemiExpanded-SemiBold.woff2
  lib/build/less/variables/typography.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
  package-lock.json
  package.json
Labels: bug

#430 add some missing spacing unit CSS vars
  docs/_data/spacing.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/design/spacing/spacing-system.html
  lib/build/less/variables/spacing.less
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
Labels: documentation, v6

#433 Added Dialtone 5 cross-link, top-banner
  docs/_includes/banner.html
  docs/_includes/layouts/page-home.html
  docs/_includes/layouts/page-no-toc.html
  docs/_includes/layouts/page.html
  docs/_includes/nav.html
  docs/assets/js/banner.js
  docs/assets/js/nav.js
Labels: documentation, v6

#435 Updated CSS badge endpoint
  docs/index.html
Labels: bug

#434 V6: Added new brand icons
  docs/_data/svg-brand.json
  docs/_includes/icons/brand/front.svg
  docs/_includes/icons/brand/gmail.svg
  docs/_includes/icons/brand/google-calendar.svg
  docs/_includes/icons/brand/google-docs.svg
  docs/_includes/icons/brand/google-drive.svg
  docs/_includes/icons/brand/microsoft-dynamics-365.svg
  docs/_includes/icons/brand/microsoft.svg
  docs/_includes/icons/brand/office-365.svg
  lib/build/svg/brand/front.svg
  lib/build/svg/brand/gmail.svg
  lib/build/svg/brand/google-calendar.svg
  lib/build/svg/brand/google-docs.svg
  lib/build/svg/brand/google-drive.svg
  lib/build/svg/brand/microsoft-dynamics-365.svg
  lib/build/svg/brand/microsoft.svg
  lib/build/svg/brand/office-365.svg
  lib/dist/svg/brand/front.svg
  lib/dist/svg/brand/gmail.svg
  lib/dist/svg/brand/google-calendar.svg
  lib/dist/svg/brand/google-docs.svg
  lib/dist/svg/brand/google-drive.svg
  lib/dist/svg/brand/microsoft-dynamics-365.svg
  lib/dist/svg/brand/microsoft.svg
  lib/dist/svg/brand/office-365.svg
  lib/dist/vue/icons/IconFront.vue
  lib/dist/vue/icons/IconGmail.vue
  lib/dist/vue/icons/IconGoogleCalendar.vue
  lib/dist/vue/icons/IconGoogleDocs.vue
  lib/dist/vue/icons/IconGoogleDrive.vue
  lib/dist/vue/icons/IconMicrosoft.vue
  lib/dist/vue/icons/IconMicrosoftDynamics365.vue
  lib/dist/vue/icons/IconOffice365.vue
Labels: v6, icon

#432 Updating brand icons
  docs/_data/svg-brand.json
  docs/_includes/icons/brand/front.svg
  docs/_includes/icons/brand/gmail.svg
  docs/_includes/icons/brand/google-calendar.svg
  docs/_includes/icons/brand/google-docs.svg
  docs/_includes/icons/brand/google-drive.svg
  docs/_includes/icons/brand/microsoft-dynamics-365.svg
  docs/_includes/icons/brand/microsoft.svg
  docs/_includes/icons/brand/office-365.svg
  docs/assets/css/dialtone--syntax.css
  docs/assets/css/dialtone--syntax.min.css
  lib/build/svg/brand/front.svg
  lib/build/svg/brand/gmail.svg
  lib/build/svg/brand/google-calendar.svg
  lib/build/svg/brand/google-docs.svg
  lib/build/svg/brand/google-drive.svg
  lib/build/svg/brand/microsoft-dynamics-365.svg
  lib/build/svg/brand/microsoft.svg
  lib/build/svg/brand/office-365.svg
  lib/dist/svg/brand/front.svg
  lib/dist/svg/brand/gmail.svg
  lib/dist/svg/brand/google-calendar.svg
  lib/dist/svg/brand/google-docs.svg
  lib/dist/svg/brand/google-drive.svg
  lib/dist/svg/brand/microsoft-dynamics-365.svg
  lib/dist/svg/brand/microsoft.svg
  lib/dist/svg/brand/office-365.svg
  lib/dist/vue/icons/IconFront.vue
  lib/dist/vue/icons/IconGmail.vue
  lib/dist/vue/icons/IconGoogleCalendar.vue
  lib/dist/vue/icons/IconGoogleDocs.vue
  lib/dist/vue/icons/IconGoogleDrive.vue
  lib/dist/vue/icons/IconMicrosoft.vue
  lib/dist/vue/icons/IconMicrosoftDynamics365.vue
  lib/dist/vue/icons/IconOffice365.vue
Labels: icon

#444 Add icon for "Done All"
  docs/_data/svg-system.json
  docs/_includes/icons/system/done-all.svg
  lib/build/svg/system/done-all.svg
  lib/dist/svg/system/done-all.svg
  lib/dist/vue/icons/IconDoneAll.vue
Labels: icon

#445 Adding done-all icon
  docs/_data/svg-system.json
  docs/_includes/icons/system/done-all.svg
  lib/build/svg/system/done-all.svg
  lib/dist/css/dialtone.css
  lib/dist/css/dialtone.min.css
  lib/dist/svg/system/done-all.svg
  lib/dist/vue/icons/IconDoneAll.vue
Labels: v6, icon

#449 DT-142 update Inter to latest version
  lib/build/fonts/Inter-Bold.woff2
  lib/build/fonts/Inter-BoldItalic.woff2
  lib/build/fonts/Inter-Italic.woff2
  lib/build/fonts/Inter-Regular.woff2
Labels: bug
