Repository dialpad/dialtone, pull requests merged in 2021-03, with the labels that each got.

#191 Added volume icons
  docs/_data/svg-system.json
  docs/_includes/icons/system/volume-down.svg
  docs/_includes/icons/system/volume-mute.svg
  docs/_includes/icons/system/volume-off.svg
  docs/_includes/icons/system/volume-up.svg
  docs/assets/css/dialtone--syntax.css
  docs/assets/css/dialtone--syntax.min.css
  lib/build/svg/system/volume-down.svg
  lib/build/svg/system/volume-mute.svg
  lib/build/svg/system/volume-off.svg
  lib/build/svg/system/volume-up.svg
  lib/dist/svg/system/volume-down.svg
  lib/dist/svg/system/volume-mute.svg
  lib/dist/svg/system/volume-off.svg
  lib/dist/svg/system/volume-up.svg
  lib/dist/vue/icons/IconVolumeDown.vue
  lib/dist/vue/icons/IconVolumeMute.vue
  lib/dist/vue/icons/IconVolumeOff.vue
  lib/dist/vue/icons/IconVolumeUp.vue
Labels: enhancement

#198 Add Miro app brand icon
  docs/_data/svg-brand.json
  docs/_includes/icons/brand/miro.svg
  lib/build/svg/brand/miro.svg
  lib/dist/svg/brand/miro.svg
  lib/dist/vue/icons/IconMiro.vue
Labels: icon

#202 Add shortcodes
  docs/.eleventy.js
  docs/_data/breadcrumbs.json
  docs/_includes/layouts/page.html
  docs/components/banners.html
  docs/components/breadcrumbs.html
  docs/utilities/flex/align-content.html
Labels: documentation, v6

#201 Dialtone V6 Component Tooltip Implementation
  docs/_includes/header.html
  docs/components/tooltips.html
  lib/less/components/tooltips.less
Labels: v6

#204 V6 component tooltip docs
  docs/.eleventy.js
  docs/_data/tooltips.json
  docs/components/tooltips.html
Labels: documentation, v6

#230 Dialtone V6 Component Validation Message Implementation
  lib/less/components/validation-messages.less
  lib/less/dialtone.less
Labels: v6

#232 Dialtone V6 Component Validation Message Docs
  docs/components/checkboxes.html
  docs/components/radios.html
Labels: v6

#233 V6 component validation message
  docs/components/checkboxes.html
  docs/components/radios.html
  lib/less/components/validation-messages.less
  lib/less/dialtone.less
Labels: v6

#224 Dialtone V6 Components Radio & Checkbox Implementations
  docs/components/checkboxes.html
  docs/components/radios.html
  lib/less/components/radio-checkbox.less
Labels: v6

#234 Dialtone V6 Component Breadcrumbs Implementation
  docs/_data/breadcrumbs.json
  docs/components/breadcrumbs.html
  lib/less/components/breadcrumbs.less
  lib/less/components/links.less
  lib/less/variables/colors.less
Labels: v6

#241 Icon/arrow keyboard up and filmstrip
  docs/_data/svg-system.json
  docs/_includes/icons/system/arrow-keyboard-up.svg
  docs/_includes/icons/system/filmstrip-layout.svg
  lib/build/svg/system/arrow-keyboard-up.svg
  lib/build/svg/system/filmstrip-layout.svg
  lib/dist/svg/system/arrow-keyboard-up.svg
  lib/dist/svg/system/filmstrip-layout.svg
  lib/dist/vue/icons/IconArrowKeyboardUp.vue
  lib/dist/vue/icons/IconFilmstripLayout.vue
Labels: icon

#244 V6 component breadcrumbs
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/breadcrumbs.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/breadcrumbs.html
  lib/less/components/breadcrumbs.less
  lib/less/components/links.less
  lib/less/variables/colors.less
Labels: v6

#242 Dialtone V6 Components Banner and Notice Implementations
  docs/assets/js/banners.js
  docs/assets/js/notices.js
  docs/components/banners.html
  docs/components/notices.html
  lib/less/components/banners.less
  lib/less/components/notices.less
Labels: v6

#247 Svg utilities
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/utilities/svg/fill.html
  docs/utilities/svg/size.html
  lib/less/utilities/colors.less
Labels: v6

#249 Interactivity utilities
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/interactivity.json
  docs/_data/site-nav.json
  docs/_data/visual-styles.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/utilities/interactivity/cursor.html
  docs/utilities/interactivity/outline.html
  docs/utilities/interactivity/pointer-events.html
  lib/less/utilities/interactivity.less
Labels: v6

#257 Dialtone V6 Component Badge Implementation
  docs/_data/badges.json
  docs/_data/nav.json
  docs/_data/site-nav.json
  docs/components/badges.html
  lib/less/components/badges.less
  lib/less/dialtone.less
Labels: v6

#248 Dialtone V6 Component Avatar Implementation
  docs/_data/avatars.json
  docs/_data/nav.json
  docs/_data/site-nav.json
  docs/assets/images/person.png
  docs/components/avatars.html
  lib/less/components/avatars.less
  lib/less/dialtone.less
Labels: v6

#260 V6 components banner and notice
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/.eleventy.js
  docs/_data/banners.json
  docs/_data/notices.json
  docs/_includes/layouts/page.html
  docs/_includes/nav.html
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/assets/js/banners.js
  docs/assets/js/notices.js
  docs/components/banners.html
  docs/components/notices.html
  lib/less/components/banners.less
  lib/less/components/notices.less
Labels: v6

#258 Updated Tabs documentation.
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/.eleventy.js
  docs/_data/tabs.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/tabs.html
  lib/less/components/tabs.less
Labels: v6

#262 V6 component tabs
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/tabs.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/tabs.html
  lib/less/components/tabs.less
Labels: v6

#261 Badge documentation
  dist/css/dialtone.css
  dist/css/dialtone.min.css
  docs/_data/badges.json
  docs/assets/css/dialtone.css
  docs/assets/css/dialtone.min.css
  docs/components/badges.html
Labels: v6
