Repository dialpad/dialtone, pull requests merged in 2022-01, with the labels that each got.

#525 fix: svg sizes showing up as NaN in svg utility class page
  docs/_data/icons-sizes.json
  docs/utilities/svg/size.html
Labels: bug

#527 feat: add file upload spot illustration
  docs/_data/svg-spot.json
  lib/build/svg/spot/file-upload.svg
Labels: icons

#533 feat: add toggle styles
  docs/_data/site-nav.json
  docs/_data/toggle.json
  docs/assets/js/toggle.js
  docs/components/toggle.html
  lib/build/less/components/toggle.less
  lib/build/less/dialtone.less
Labels: enhancement
