Repository dialpad/dialtone, pull requests merged in 2024-01, with the labels that each got.

#80 fix: update on the Video icon to have a better visual balance
  packages/dialtone-icons/src/svg/devices/video-off.svg
  packages/dialtone-icons/src/svg/devices/video.svg
Labels: no-visual-test

#78 feat: port contact suggestion
  packages/dialtone-vue2/components/rich_text_editor/extensions/mentions/MentionComponent.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/mentions/MentionSuggestion.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/mentions/mention.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/mentions/suggestion.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/suggestion/SuggestionList.vue
  packages/dialtone-vue2/components/rich_text_editor/mention_suggestion.js
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor.mdx
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor.stories.js
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor.vue
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor_default.story.vue
Labels: no-visual-test

#77 feat: port emoji suggestions
  .github/workflows/unit_tests.yml
  .github/workflows/visual_tests.yml
  packages/dialtone-vue2/.github/TEST_CONTRIBUTING/test_template.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/EmojiComponent.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/EmojiSuggestion.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/emoji.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/emoji.test.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/index.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/suggestion.js
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor.stories.js
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor.vue
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor_default.story.vue
  packages/dialtone-vue3/.github/TEST_CONTRIBUTING/test_template.js
  packages/dialtone-vue3/components/hovercard/hovercard.test.js
Labels: no-visual-test

#79 chore: gha workflow improvements
  .github/workflows/release.yml
  .github/workflows/visual_tests.yml
Labels: no-visual-test

#82 docs: update PR template for monorepo
  .github/pull_request_template.md
  packages/dialtone-vue2/pull_request_template.md
  packages/dialtone-vue3/pull_request_template.md
Labels: no-visual-test

#85 docs: fix storybook reactivity
  packages/dialtone-vue2/common/storybook_utils.js
  packages/dialtone-vue2/components/avatar/avatar.vue
  packages/dialtone-vue2/components/badge/badge.stories.js
Labels: no-visual-test

#87 feat: added unread and rematch icons
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/communication/unread.svg
  packages/dialtone-icons/src/svg/people/user-rematch.svg
Labels: no-visual-test

#89 fix: error in stories when component.props is undefined
  packages/dialtone-vue2/common/storybook_utils.js
Labels: visual-test-ready

#90 docs: fix datepicker table dark mode
  packages/dialtone-vue2/components/datepicker/datepicker_default.story.vue
  packages/dialtone-vue3/components/datepicker/datepicker_default.story.vue
Labels: no-visual-test

#99 fix: video-off icon issue
  packages/dialtone-icons/src/svg/devices/video-off.svg
Labels: no-visual-test

#91 docs: fix links starting with /
  apps/dialtone-documentation/docs/about/whats-new/posts/2023-8-3.md
  apps/dialtone-documentation/docs/components/avatar.md
  apps/dialtone-documentation/docs/guides/getting-started/index.md
  apps/dialtone-documentation/docs/guides/writing-guidelines/index.md
  apps/dialtone-documentation/docs/utilities/index.md
  apps/dialtone-documentation/docs/utilities/spacing/margin.md
Labels: no-visual-test

#93 chore: sync figma tokens
  .github/workflows/sync-figma-to-tokens.yml
  .github/workflows/sync-tokens-to-figma.yml
  packages/dialtone-tokens/.gitignore
  packages/dialtone-tokens/package.json
  packages/dialtone-tokens/sync-scripts/color.test.ts
  packages/dialtone-tokens/sync-scripts/color.ts
  packages/dialtone-tokens/sync-scripts/figma_api.ts
  packages/dialtone-tokens/sync-scripts/sync_figma_to_tokens.ts
  packages/dialtone-tokens/sync-scripts/sync_tokens_to_figma.ts
  packages/dialtone-tokens/sync-scripts/token_export.test.ts
  packages/dialtone-tokens/sync-scripts/token_export.ts
  packages/dialtone-tokens/sync-scripts/token_import.test.ts
  packages/dialtone-tokens/sync-scripts/token_import.ts
  packages/dialtone-tokens/sync-scripts/token_types.ts
  packages/dialtone-tokens/sync-scripts/utils.ts
  packages/dialtone-tokens/tsconfig.json
  pnpm-lock.yaml
Labels: no-visual-test

#102 fix: emoji_picker box-sizing
  packages/dialtone-css/lib/build/less/components/emoji-picker.less
Labels: visual-test-ready

#103 fix(hovercard): timer for vue 2
  packages/dialtone-vue2/components/hovercard/timer.js
  packages/dialtone-vue2/components/popover/popover.vue
Labels: no-visual-test

#104 fix: nx affected dependencies
  apps/dialtone-documentation/project.json
  nx.json
  packages/dialtone-css/project.json
  packages/dialtone-icons/project.json
  packages/dialtone-tokens/project.json
  packages/dialtone-vue2/project.json
  packages/dialtone-vue3/project.json
  packages/eslint-plugin-dialtone/project.json
  project.json
Labels: no-visual-test

#97 docs: adjusted background on utilities examples
  apps/dialtone-documentation/docs/utilities/backgrounds/color.md
  apps/dialtone-documentation/docs/utilities/flex/align-content.md
  apps/dialtone-documentation/docs/utilities/flex/align-items.md
  apps/dialtone-documentation/docs/utilities/flex/align-self.md
  apps/dialtone-documentation/docs/utilities/flex/direction-wrap-flow.md
  apps/dialtone-documentation/docs/utilities/flex/flex-grow-shrink.md
  apps/dialtone-documentation/docs/utilities/flex/justify.md
  apps/dialtone-documentation/docs/utilities/grid/justify-self.md
  apps/dialtone-documentation/docs/utilities/grid/layouts.md
  apps/dialtone-documentation/docs/utilities/grid/place-content.md
  apps/dialtone-documentation/docs/utilities/grid/place-items.md
  apps/dialtone-documentation/docs/utilities/grid/place-self.md
  apps/dialtone-documentation/docs/utilities/grid/row-start-end-span.md
  apps/dialtone-documentation/docs/utilities/typography/font-color.md
Labels: documentation, no-visual-test

#50 docs: added icons section in design language
  apps/dialtone-documentation/docs/.vuepress/public/assets/images/figma-search-icon.gif
  apps/dialtone-documentation/docs/_data/site-nav.json
  apps/dialtone-documentation/docs/components/icon.md
  apps/dialtone-documentation/docs/design/icons/index.md
Labels: documentation, no-visual-test

#100 docs: added update url with search value
  apps/dialtone-documentation/docs/.vuepress/baseComponents/IconPopover.vue
  apps/dialtone-documentation/docs/.vuepress/views/IconCatalog.vue
Labels: no-visual-test

#110 fix: Icons Update
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/arrows/rematch.svg
  packages/dialtone-icons/src/svg/communication/unread.svg
Labels: no-visual-test

#109 fix(feed-item-row): spacing and transition improvements - Vue 2
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.stories.js
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.test.js
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row_constants.js
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row_variants.story.vue
Labels: visual-test-ready

#106 fix: input focus within
  packages/dialtone-css/lib/build/less/components/input.less
Labels: no-visual-test

#116 fix: icon dt-ai alignment adjust
  packages/dialtone-icons/src/svg/brand-full-color/dialpad-ai-color.svg
Labels: no-visual-test

#118 feat: datepicker full language support
  packages/dialtone-vue2/components/datepicker/datepicker.test.js
  packages/dialtone-vue2/components/datepicker/datepicker.vue
  packages/dialtone-vue2/components/datepicker/datepicker_constants.js
  packages/dialtone-vue2/components/datepicker/datepicker_default.story.vue
  packages/dialtone-vue2/components/datepicker/formatUtils.js
  packages/dialtone-vue2/components/datepicker/modules/month-year-picker.vue
  packages/dialtone-vue2/components/datepicker/utils.js
  packages/dialtone-vue3/components/datepicker/composables/useMonthYearPicker.js
  packages/dialtone-vue3/components/datepicker/datepicker.test.js
  packages/dialtone-vue3/components/datepicker/datepicker.vue
  packages/dialtone-vue3/components/datepicker/datepicker_constants.js
  packages/dialtone-vue3/components/datepicker/datepicker_default.story.vue
  packages/dialtone-vue3/components/datepicker/formatUtils.js
  packages/dialtone-vue3/components/datepicker/modules/month-year-picker.vue
  packages/dialtone-vue3/components/datepicker/utils.js
Labels: no-visual-test

#105 chore: add CONTRIBUTING.md page to Dialtone Icons
  .github/CONTRIBUTING.md
  packages/dialtone-icons/.github/CONTRIBUTING.md
Labels: no-visual-test

#114 fix(general-row): map digital type to laptop-2
  packages/dialtone-vue2/recipes/leftbar/general_row/general_row_constants.js
  packages/dialtone-vue3/recipes/leftbar/general_row/general_row_constants.js
Labels: no-visual-test

#119 feat: add summary icon
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/editing/summary.svg
Labels: no-visual-test

#38 feat: added new docs for spacing in design language
  apps/dialtone-documentation/docs/.vuepress/baseComponents/TokenTable.vue
  apps/dialtone-documentation/docs/.vuepress/public/assets/images/size-img.svg
  apps/dialtone-documentation/docs/.vuepress/public/assets/images/space-img.svg
  apps/dialtone-documentation/docs/_data/site-nav.json
  apps/dialtone-documentation/docs/design/size/index.md
  apps/dialtone-documentation/docs/design/space/index.md
  apps/dialtone-documentation/docs/tokens/sizing.md
  apps/dialtone-documentation/docs/tokens/spacing.md
Labels: documentation, visual-test-ready

#123 feat(icons): added new alignment icons
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/editing/align-center.svg
  packages/dialtone-icons/src/svg/editing/align-justify.svg
  packages/dialtone-icons/src/svg/editing/align-left.svg
  packages/dialtone-icons/src/svg/editing/align-right.svg
Labels: no-visual-test

#120 ci: alpha/beta releases
  .github/workflows/release.yml
  README.md
  package.json
  packages/dialtone-tokens/package.json
  scripts/release.sh
Labels: no-visual-test

#124 fix: datepicker keyboard navigation fix vue2 only
  packages/dialtone-vue2/components/datepicker/modules/calendar.vue
  packages/dialtone-vue2/components/datepicker/modules/month-year-picker.vue
Labels: no-visual-test

#126 fix(feed-item-row, emoji-row): spacing / color fixes
  packages/dialtone-vue2/.storybook/preview-head.html
  packages/dialtone-vue2/recipes/conversation_view/emoji_row/emoji_row.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
Labels: visual-test-ready

#133 chore: rename markdownlint config
  .markdownlint.json
  apps/dialtone-documentation/.markdownlint.json
Labels: no-visual-test

#137 fix: name of the office365-calendar icon
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/brand-full-color/o365-calendar.svg
Labels: no-visual-test

#134 fix(feed-item-row, emoji-row): spacing / color fixes - Vue 3
  packages/dialtone-vue3/.storybook/preview-head.html
  packages/dialtone-vue3/recipes/conversation_view/emoji_row/emoji_row.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
Labels: visual-test-ready

#138 fix: change padding on right slot of call pill stories
  packages/dialtone-vue2/recipes/conversation_view/feed_pill/feed_item_pill.mdx
  packages/dialtone-vue2/recipes/conversation_view/feed_pill/feed_item_pill_default.story.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_pill/feed_item_pill_variants.story.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_pill/feed_item_pill.mdx
  packages/dialtone-vue3/recipes/conversation_view/feed_pill/feed_item_pill_default.story.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_pill/feed_item_pill_variants.story.vue
Labels: no-visual-test
