Repository dialpad/dialtone, pull requests merged in 2024-07, with the labels that each got.

#389 fix(emoji-picker): DP-102475 fix keyboard navigation
  packages/dialtone-icons/src/keywords-icons.json
  packages/dialtone-vue2/components/emoji_picker/emoji_picker.test.js
  packages/dialtone-vue2/components/emoji_picker/emoji_picker.vue
  packages/dialtone-vue2/components/emoji_picker/modules/emoji_selector.vue
  packages/dialtone-vue2/components/emoji_picker/modules/emoji_tabset.vue
  packages/dialtone-vue3/components/emoji_picker/emoji_picker.test.js
  packages/dialtone-vue3/components/emoji_picker/emoji_picker.vue
  packages/dialtone-vue3/components/emoji_picker/modules/emoji_selector.vue
  packages/dialtone-vue3/components/emoji_picker/modules/emoji_tabset.vue
Labels: no-visual-test

#387 feat(icon): DLT-1804 add t-mobile
  packages/dialtone-icons/src/keywords-icons.json
  packages/dialtone-icons/src/svg/icons/brand-full-color/t-mobile.svg
Labels: no-visual-test

#390 feat(rich-text-editor): DLT-1835 add undo behaviour
  packages/dialtone-icons/src/keywords-icons.json
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor.vue
  packages/dialtone-vue2/package.json
  packages/dialtone-vue3/components/rich_text_editor/rich_text_editor.vue
  packages/dialtone-vue3/package.json
  pnpm-lock.yaml
Labels: no-visual-test

#395 fix(input): NO-JIRA autocomplete attr override
  packages/dialtone-vue2/components/input/input.test.js
  packages/dialtone-vue2/components/input/input.vue
  packages/dialtone-vue2/components/input/input_default.story.vue
  packages/dialtone-vue3/components/input/input.test.js
  packages/dialtone-vue3/components/input/input.vue
  packages/dialtone-vue3/components/input/input_default.story.vue
Labels: no-visual-test

#392 feat(input): DLT-1808 icon scoped slot
  apps/dialtone-documentation/docs/components/input.md
  packages/dialtone-css/lib/build/less/components/input.less
  packages/dialtone-vue2/components/input/input.mdx
  packages/dialtone-vue2/components/input/input.stories.js
  packages/dialtone-vue2/components/input/input.test.js
  packages/dialtone-vue2/components/input/input.vue
  packages/dialtone-vue2/components/input/input_constants.js
  packages/dialtone-vue2/components/input/input_default.story.vue
  packages/dialtone-vue3/components/input/input.mdx
  packages/dialtone-vue3/components/input/input.stories.js
  packages/dialtone-vue3/components/input/input.test.js
  packages/dialtone-vue3/components/input/input.vue
  packages/dialtone-vue3/components/input/input_constants.js
  packages/dialtone-vue3/components/input/input_default.story.vue
Labels: visual-test-ready

#393 fix(emoji-picker): NO-JIRA fix keyboard proposal
  packages/dialtone-vue2/components/emoji_picker/emoji_picker.vue
  packages/dialtone-vue2/components/emoji_picker/modules/emoji_selector.vue
  packages/dialtone-vue2/components/emoji_picker/modules/emoji_tabset.vue
  packages/dialtone-vue3/components/emoji_picker/emoji_picker.vue
  packages/dialtone-vue3/components/emoji_picker/modules/emoji_selector.vue
  packages/dialtone-vue3/components/emoji_picker/modules/emoji_tabset.vue
Labels: no-visual-test

#400 fix(emoji-picker): DLT-1864 tabs not focusing properly
  packages/dialtone-vue2/components/emoji_picker/modules/emoji_selector.vue
  packages/dialtone-vue3/components/emoji_picker/modules/emoji_selector.vue
Labels: no-visual-test

#401 fix(input): NO-JIRA add identifier classes
  packages/dialtone-css/lib/build/less/components/input.less
  packages/dialtone-vue2/components/input/input.vue
  packages/dialtone-vue2/components/input/input_constants.js
  packages/dialtone-vue3/components/input/input.vue
  packages/dialtone-vue3/components/input/input_constants.js
Labels: visual-test-ready

#397 docs: DLT-1787 implement custom TOC
  apps/dialtone-documentation/docs/.vuepress/baseComponents/tokens/AllTokens.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/tokens/TokensToc.vue
  apps/dialtone-documentation/docs/.vuepress/theme/assets/less/dialtone-docs.less
  apps/dialtone-documentation/docs/.vuepress/theme/components/Page.vue
  apps/dialtone-documentation/docs/.vuepress/theme/components/PageToc.vue
  apps/dialtone-documentation/docs/.vuepress/theme/components/TocItem.vue
  apps/dialtone-documentation/docs/.vuepress/theme/index.js
  apps/dialtone-documentation/package.json
  pnpm-lock.yaml
Labels: no-visual-test

#394 feat(multi-select): DLT-1845 allow duplicated names on multiselect
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.stories.js
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.test.js
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  packages/dialtone-vue3/recipes/comboboxes/combobox_multi_select/combobox_multi_select.stories.js
Labels: no-visual-test

#403 docs(logo): DLT-1866 modify dialtone documentation logo
  apps/dialtone-documentation/docs/.vuepress/theme/components/DialtoneLogo.vue
  pnpm-lock.yaml
Labels: documentation, no-visual-test

#404 feat(design-tokens): DLT-1870 additional expressive typography tokens
  packages/dialtone-tokens/tokens/$themes.json
  packages/dialtone-tokens/tokens/semantic/expressive/default.json
Labels: no-visual-test

#405 feat(design-tokens): DLT-1871 added gold brand color
  packages/dialtone-tokens/tokens/$themes.json
  packages/dialtone-tokens/tokens/base/default.json
Labels: no-visual-test

#391 feat(scrollbar): DLT-1473 add scrollbar directive
  apps/dialtone-documentation/docs/.vuepress/baseComponents/CodeExampleTabs.vue
  apps/dialtone-documentation/docs/.vuepress/public/assets/images/components/scrollbar.png
  apps/dialtone-documentation/docs/.vuepress/public/assets/images/components/scrollbar.svg
  apps/dialtone-documentation/docs/_data/site-nav.json
  apps/dialtone-documentation/docs/components/scrollbar.md
  packages/dialtone-css/lib/build/less/components/scrollbar.less
  packages/dialtone-css/lib/build/less/dialtone.less
  packages/dialtone-vue2/.storybook/preview.jsx
  packages/dialtone-vue2/directives/scrollbar/index.js
  packages/dialtone-vue2/directives/scrollbar/scrollbar.js
  packages/dialtone-vue2/directives/scrollbar/scrollbar.test.js
  packages/dialtone-vue2/index.js
  packages/dialtone-vue2/package.json
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.vue
  packages/dialtone-vue3/.storybook/preview.jsx
  packages/dialtone-vue3/directives/scrollbar/index.js
  packages/dialtone-vue3/directives/scrollbar/scrollbar.js
  packages/dialtone-vue3/directives/scrollbar/scrollbar.test.js
  packages/dialtone-vue3/index.js
  packages/dialtone-vue3/package.json
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.vue
  pnpm-lock.yaml
Labels: no-visual-test

#402 fix(rich-text-editor): NO-JIRA multiple improvements
  packages/dialtone-vue2/components/hovercard/hovercard_many.story.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/channels/suggestion.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/suggestion.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/mentions/suggestion.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/slash_command/SlashCommandSuggestion.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/slash_command/suggestion.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/suggestion/SuggestionList.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/tippy_plugins/hide_on_esc.js
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor.stories.js
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor.vue
  packages/dialtone-vue2/components/rich_text_editor/rich_text_editor_default.story.vue
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.stories.js
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.test.js
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.vue
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input_default.story.vue
  packages/dialtone-vue3/components/hovercard/hovercard_many.story.vue
  packages/dialtone-vue3/components/rich_text_editor/extensions/channels/suggestion.js
  packages/dialtone-vue3/components/rich_text_editor/extensions/emoji/suggestion.js
  packages/dialtone-vue3/components/rich_text_editor/extensions/mentions/suggestion.js
  packages/dialtone-vue3/components/rich_text_editor/extensions/slash_command/SlashCommandSuggestion.vue
  packages/dialtone-vue3/components/rich_text_editor/extensions/slash_command/suggestion.js
  packages/dialtone-vue3/components/rich_text_editor/extensions/suggestion/SuggestionList.vue
  packages/dialtone-vue3/components/rich_text_editor/extensions/tippy_plugins/hide_on_esc.js
  packages/dialtone-vue3/components/rich_text_editor/rich_text_editor.stories.js
  packages/dialtone-vue3/components/rich_text_editor/rich_text_editor.vue
  packages/dialtone-vue3/components/rich_text_editor/rich_text_editor_default.story.vue
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.stories.js
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.test.js
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.vue
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input_default.story.vue
Labels: visual-test-ready

#408 [Fix] Changes in Figma tokens files - enabled to source
  packages/dialtone-tokens/tokens/$themes.json
Labels: no-visual-test

#399 feat(combobox-multiselect): NO-JIRA add collapse on focus out
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.stories.js
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select_default.story.vue
  packages/dialtone-vue3/recipes/comboboxes/combobox_multi_select/combobox_multi_select.stories.js
  packages/dialtone-vue3/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  packages/dialtone-vue3/recipes/comboboxes/combobox_multi_select/combobox_multi_select_default.story.vue
Labels: visual-test-ready

#406 chore(documentation-site): NO-JIRA enhance sidebar
  .gitignore
  apps/dialtone-documentation/docs/.vuepress/config.js
  apps/dialtone-documentation/docs/.vuepress/theme/components/MobileSidebar.vue
  apps/dialtone-documentation/docs/.vuepress/theme/components/PageToc.vue
  apps/dialtone-documentation/docs/.vuepress/theme/components/SidebarItem.vue
  apps/dialtone-documentation/docs/.vuepress/theme/components/TocItem.vue
  apps/dialtone-documentation/docs/.vuepress/theme/index.js
  apps/dialtone-documentation/docs/.vuepress/theme/layouts/Layout.vue
  apps/dialtone-documentation/docs/_data/site-nav.json
  apps/dialtone-documentation/docs/content/index.md
  apps/dialtone-documentation/docs/guides/accessibility/index.md
  apps/dialtone-documentation/docs/guides/content/action-language/index.md
  apps/dialtone-documentation/docs/guides/content/error-messages/index.md
  apps/dialtone-documentation/docs/guides/content/grammar-mechanics/index.md
  apps/dialtone-documentation/docs/guides/content/help-content/index.md
  apps/dialtone-documentation/docs/guides/content/inclusive-language/index.md
  apps/dialtone-documentation/docs/guides/content/index.md
  apps/dialtone-documentation/docs/guides/content/voice-tone/index.md
Labels: no-visual-test

#410 fix(multi-select): NO-JIRA update input padding when focus out
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  packages/dialtone-vue3/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
Labels: no-visual-test

#411 docs: DLT-1794 move storybook to doc site Datepicker to Dropdown
  apps/dialtone-documentation/docs/.vuepress/baseComponents/CodeExampleTabs.vue
  apps/dialtone-documentation/docs/.vuepress/theme/client.js
  apps/dialtone-documentation/docs/_data/site-nav.json
  apps/dialtone-documentation/docs/components/datepicker.md
  apps/dialtone-documentation/docs/components/description-list.md
  apps/dialtone-documentation/docs/components/dropdown.md
  packages/dialtone-vue2/components/datepicker/datepicker.mdx
  packages/dialtone-vue2/components/datepicker/formatUtils.js
  packages/dialtone-vue2/components/description_list/description_list.mdx
  packages/dialtone-vue2/components/dropdown/dropdown.mdx
  packages/dialtone-vue3/components/datepicker/datepicker.mdx
  packages/dialtone-vue3/components/description_list/description_list.mdx
  packages/dialtone-vue3/components/dropdown/dropdown.mdx
Labels: no-visual-test

#407 fix(emoji-text-wrapper): DLT-1699 emoji alignment
  packages/dialtone-css/lib/build/less/components/emoji-text-wrapper.less
  packages/dialtone-vue2/components/emoji/emoji.vue
  packages/dialtone-vue2/components/emoji/emoji_variants.story.vue
  packages/dialtone-vue2/components/emoji_text_wrapper/emoji_text_wrapper.stories.js
  packages/dialtone-vue2/components/emoji_text_wrapper/emoji_text_wrapper.vue
  packages/dialtone-vue2/components/emoji_text_wrapper/emoji_text_wrapper_variants.story.vue
  packages/dialtone-vue2/recipes/leftbar/general_row/general_row_variants.story.vue
  packages/dialtone-vue2/recipes/leftbar/style/leftbar_row.less
  packages/dialtone-vue3/components/emoji/emoji.vue
  packages/dialtone-vue3/components/emoji/emoji_variants.story.vue
  packages/dialtone-vue3/components/emoji_text_wrapper/emoji_text_wrapper.stories.js
  packages/dialtone-vue3/components/emoji_text_wrapper/emoji_text_wrapper.vue
  packages/dialtone-vue3/components/emoji_text_wrapper/emoji_text_wrapper_variants.story.vue
  packages/dialtone-vue3/recipes/leftbar/general_row/general_row_variants.story.vue
  packages/dialtone-vue3/recipes/leftbar/style/leftbar_row.less
Labels: visual-test-ready

#413 fix(multi-select): NO-JIRA update input padding when resizing
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  packages/dialtone-vue3/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
Labels: no-visual-test

#415 feat(icons): DLT-1697 add types
  README.md
  packages/dialtone-icons/README.md
  packages/dialtone-icons/gulpfile.cjs
  packages/dialtone-icons/package.json
  packages/dialtone-icons/vue2/package.json
  packages/dialtone-icons/vue2/tsconfig.json
  packages/dialtone-icons/vue2/tsconfig.vite.json
  packages/dialtone-icons/vue3/package.json
  packages/dialtone-icons/vue3/tsconfig.json
  packages/dialtone-icons/vue3/tsconfig.vite.json
  pnpm-lock.yaml
Labels: visual-test-ready

#419 feat(message-input): DLT-1912 add slot for split button
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.stories.js
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.vue
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input_default.story.vue
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.stories.js
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.vue
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input_default.story.vue
Labels: no-visual-test

#422 feat(ivr-node-assign): DP-95641 add assign step type
  packages/dialtone-vue2/recipes/cards/ivr_node/ivr_node.mdx
  packages/dialtone-vue2/recipes/cards/ivr_node/ivr_node.stories.js
  packages/dialtone-vue2/recipes/cards/ivr_node/ivr_node.test.js
  packages/dialtone-vue2/recipes/cards/ivr_node/ivr_node_constants.js
  packages/dialtone-vue2/recipes/cards/ivr_node/ivr_node_default.story.vue
  packages/dialtone-vue3/recipes/cards/ivr_node/ivr_node.mdx
  packages/dialtone-vue3/recipes/cards/ivr_node/ivr_node.stories.js
  packages/dialtone-vue3/recipes/cards/ivr_node/ivr_node.test.js
  packages/dialtone-vue3/recipes/cards/ivr_node/ivr_node_constants.js
  packages/dialtone-vue3/recipes/cards/ivr_node/ivr_node_default.story.vue
Labels: visual-test-ready

#424 fix(tooltip): DLT-1921 enabled prop not working
  packages/dialtone-vue2/components/tooltip/tooltip.test.js
  packages/dialtone-vue2/components/tooltip/tooltip.vue
Labels: no-visual-test

#425 fix(tooltip): DLT-1921 enabled prop not working - vue 3
  packages/dialtone-vue3/components/tooltip/tooltip.test.js
  packages/dialtone-vue3/components/tooltip/tooltip.vue
Labels: no-visual-test

#423 feat(leftbar): DLT-1929 add scheduled icon
  packages/dialtone-vue2/recipes/leftbar/general_row/general_row_constants.js
  packages/dialtone-vue3/recipes/leftbar/general_row/general_row_constants.js
Labels: no-visual-test

#426 fix(ivr-node-assign): DP-95641 fix constant export
  packages/dialtone-vue2/recipes/cards/ivr_node/index.js
  packages/dialtone-vue2/recipes/cards/ivr_node/ivr_node_constants.js
  packages/dialtone-vue3/recipes/cards/ivr_node/index.js
  packages/dialtone-vue3/recipes/cards/ivr_node/ivr_node_constants.js
Labels: no-visual-test
