Repository dialpad/dialtone, pull requests merged in 2024-02, with the labels that each got.

#139 fix(feed-item-row): set inset focus ring on feed item
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row.vue
Labels: no-visual-test

#117 feat(wysiwyg-editor, rich-text-editor): add wysiwyg component for vue3
  packages/dialtone-vue3/components/rich_text_editor/rich_text_editor.test.js
  packages/dialtone-vue3/components/rich_text_editor/rich_text_editor.vue
  packages/dialtone-vue3/components/rich_text_editor/rich_text_editor_constants.js
  packages/dialtone-vue3/index.js
  packages/dialtone-vue3/package.json
  packages/dialtone-vue3/recipes/conversation_view/editor/editor.mdx
  packages/dialtone-vue3/recipes/conversation_view/editor/editor.stories.js
  packages/dialtone-vue3/recipes/conversation_view/editor/editor.test.js
  packages/dialtone-vue3/recipes/conversation_view/editor/editor.vue
  packages/dialtone-vue3/recipes/conversation_view/editor/editor_constants.js
  packages/dialtone-vue3/recipes/conversation_view/editor/editor_default.story.vue
  packages/dialtone-vue3/recipes/conversation_view/editor/index.js
  pnpm-lock.yaml
Labels: visual-test-ready

#136 fix(emoji-text-wrapper): center align emojis within text
  packages/dialtone-css/lib/build/less/components/emoji-text-wrapper.less
  packages/dialtone-css/lib/build/less/components/emoji.less
  packages/dialtone-css/lib/build/less/dialtone.less
  packages/dialtone-vue2/components/emoji/emoji.vue
  packages/dialtone-vue2/components/emoji_text_wrapper/emoji_text_wrapper.stories.js
  packages/dialtone-vue2/components/emoji_text_wrapper/emoji_text_wrapper.vue
  packages/dialtone-vue2/components/emoji_text_wrapper/emoji_text_wrapper_variants.story.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/EmojiComponent.vue
  packages/dialtone-vue3/components/emoji/emoji.vue
  packages/dialtone-vue3/components/emoji_text_wrapper/emoji_text_wrapper.stories.js
  packages/dialtone-vue3/components/emoji_text_wrapper/emoji_text_wrapper.vue
  packages/dialtone-vue3/components/emoji_text_wrapper/emoji_text_wrapper_variants.story.vue
  packages/dialtone-vue3/components/rich_text_editor/extensions/emoji/EmojiComponent.vue
Labels: visual-test-ready

#140 feat: add codeblock icon
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/controls/circle-slashed.svg
  packages/dialtone-icons/src/svg/editing/code-block.svg
Labels: no-visual-test

#132 feat(tooltip): add appendTo prop to tooltip
  packages/dialtone-vue2/components/tooltip/tooltip.stories.js
  packages/dialtone-vue2/components/tooltip/tooltip.test.js
  packages/dialtone-vue2/components/tooltip/tooltip.vue
  packages/dialtone-vue2/components/tooltip/tooltip_constants.js
  packages/dialtone-vue2/components/tooltip/tooltip_default.story.vue
  packages/dialtone-vue3/components/tooltip/tooltip.stories.js
  packages/dialtone-vue3/components/tooltip/tooltip.test.js
  packages/dialtone-vue3/components/tooltip/tooltip.vue
  packages/dialtone-vue3/components/tooltip/tooltip_constants.js
  packages/dialtone-vue3/components/tooltip/tooltip_default.story.vue
Labels: no-visual-test

#143 fix(emoji-row): update emoji-row to use more semantic colors
  packages/dialtone-vue2/recipes/conversation_view/emoji_row/emoji_row.vue
  packages/dialtone-vue3/recipes/conversation_view/emoji_row/emoji_row.vue
Labels: visual-test-ready

#146 fix(tooltip): initialization issue
  packages/dialtone-vue2/components/tooltip/tooltip.stories.js
  packages/dialtone-vue2/components/tooltip/tooltip.vue
  packages/dialtone-vue2/components/tooltip/tooltip_default.story.vue
  packages/dialtone-vue3/components/tooltip/tooltip.stories.js
  packages/dialtone-vue3/components/tooltip/tooltip.vue
  packages/dialtone-vue3/components/tooltip/tooltip_default.story.vue
Labels: visual-test-ready

#144 refactor: lint pr check update
  .github/workflows/lint-pr.yml
Labels: no-visual-test

#142 fix: rich editor improvements
  apps/dialtone-documentation/docs/_data/stack.json
  packages/dialtone-css/lib/build/less/components/stack.less
  packages/dialtone-vue2/components/stack/stack_constants.js
  packages/dialtone-vue2/recipes/conversation_view/editor/editor.vue
  packages/dialtone-vue3/components/stack/stack_constants.js
  packages/dialtone-vue3/recipes/conversation_view/editor/editor.vue
Labels: no-visual-test

#147 feat: new icon user speak
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/people/user-speak.svg
Labels: no-visual-test

#149 fix(feed-item-row): change typography to compact
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.stories.js
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row.stories.js
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
Labels: visual-test-ready

#153 chore: update unit tests action
  .github/workflows/unit_tests.yml
  nx.json
  package.json
  project.json
Labels: no-visual-test

#150 fix(emoji): skeleton display issue
  packages/dialtone-vue2/components/emoji/emoji.vue
  packages/dialtone-vue3/components/emoji/emoji.vue
Labels: visual-test-ready

#156 fix(emoji-row): tooltip position when content changes
  packages/dialtone-vue2/recipes/conversation_view/emoji_row/emoji_row.vue
  packages/dialtone-vue3/recipes/conversation_view/emoji_row/emoji_row.vue
Labels: visual-test-ready

#157 feat(icons): thumbs up and down filled icons
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/general/thumbs-down-filled.svg
  packages/dialtone-icons/src/svg/general/thumbs-up-filled.svg
Labels: no-visual-test

#145 feat: universal dialtone-icons
  .eslintrc.cjs
  .gitignore
  apps/dialtone-documentation/docs/.vuepress/views/IconCatalog.vue
  apps/dialtone-documentation/package.json
  apps/dialtone-documentation/project.json
  common/utils.js
  packages/dialtone-css/package.json
  packages/dialtone-icons/.eslintignore
  packages/dialtone-icons/.eslintrc.cjs
  packages/dialtone-icons/.github/CONTRIBUTING.md
  packages/dialtone-icons/gulpfile.cjs
  packages/dialtone-icons/index.js
  packages/dialtone-icons/package.json
  packages/dialtone-icons/project.json
  packages/dialtone-icons/src/IconTemplate.vue
  packages/dialtone-icons/src/icons/index.js
  packages/dialtone-icons/transformSVGtoVue.cjs
  packages/dialtone-icons/vue2/package.json
  packages/dialtone-icons/vue2/project.json
  packages/dialtone-icons/vue2/vite.config.js
  packages/dialtone-icons/vue3/package.json
  packages/dialtone-icons/vue3/project.json
  packages/dialtone-icons/vue3/vite.config.js
  packages/dialtone-tokens/build-sd-transforms.js
  packages/dialtone-vue2/.storybook/preview.jsx
  packages/dialtone-vue2/common/storybook_utils.js
  packages/dialtone-vue2/components/icon/icon.vue
  packages/dialtone-vue2/components/icon/icon_variants.story.vue
  packages/dialtone-vue2/generator-dialtone-vue/package.json
  packages/dialtone-vue2/package.json
  packages/dialtone-vue2/project.json
  packages/dialtone-vue2/vite.config.js
  packages/dialtone-vue3/.storybook/preview.jsx
  packages/dialtone-vue3/common/storybook_utils.js
  packages/dialtone-vue3/components/icon/icon.vue
  packages/dialtone-vue3/components/icon/icon_variants.story.vue
  packages/dialtone-vue3/generator-dialtone-vue/package.json
  packages/dialtone-vue3/package.json
  packages/dialtone-vue3/project.json
  packages/dialtone-vue3/vite.config.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
  project.json
Labels: visual-test-ready

#158 chore: fix release
  .github/workflows/release.yml
  packages/dialtone-css/project.json
  packages/dialtone-icons/project.json
  packages/dialtone-tokens/project.json
  packages/dialtone-vue2/project.json
  packages/dialtone-vue3/project.json
  packages/eslint-plugin-dialtone/project.json
  project.json
  scripts/release.sh
Labels: no-visual-test

#159 fix: dist exports
  package.json
Labels: no-visual-test

#162 fix: tooltip misplaced
  packages/dialtone-css/lib/build/less/components/tooltip.less
Labels: visual-test-ready

#163 ci: only release android if tokens changed
  .github/workflows/release.yml
Labels: no-visual-test

#164 fix: tooltip directive reactive
  packages/dialtone-vue2/directives/tooltip/tooltip.js
  packages/dialtone-vue3/directives/tooltip/tooltip.js
Labels: no-visual-test

#165 fix(popover): reading from undefined ref
  packages/dialtone-vue2/components/popover/popover.vue
  packages/dialtone-vue3/components/popover/popover.vue
Labels: no-visual-test

#166 fix(feed-item-row): left line height
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row.vue
Labels: no-visual-test

#169 fix(tooltip): remove validators from directive
  packages/dialtone-vue2/directives/tooltip/tooltip.js
  packages/dialtone-vue2/directives/tooltip/tooltip_directive_default.story.vue
  packages/dialtone-vue3/directives/tooltip/tooltip.js
  packages/dialtone-vue3/directives/tooltip/tooltip_directive_default.story.vue
Labels: no-visual-test

#154 feat: transform Figma variables to sd format
  packages/dialtone-tokens/.eslintrc.cjs
  packages/dialtone-tokens/.github/CONTRIBUTING.md
  packages/dialtone-tokens/dialtone-transforms.js
  packages/dialtone-tokens/figma_tokens/base.global.json
  packages/dialtone-tokens/figma_tokens/components.global.json
  packages/dialtone-tokens/figma_tokens/root.value.json
  packages/dialtone-tokens/package.json
  packages/dialtone-tokens/sync-scripts/sync_figma_to_tokens.ts
  packages/dialtone-tokens/sync-scripts/sync_tokens_to_figma.ts
  packages/dialtone-tokens/sync-scripts/token_export.ts
  packages/dialtone-tokens/sync-scripts/token_types.ts
  packages/dialtone-tokens/sync-scripts/transform.ts
  packages/dialtone-tokens/tokens/base/default.json
  pnpm-lock.yaml
Labels: no-visual-test

#171 feat: added new dialpad ai reversed icons
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-icons/src/svg/brand-full-color/dialpad-ai-color-reversed.svg
  packages/dialtone-icons/src/svg/brand/dialpad-ai-reversed.svg
Labels: no-visual-test

#167 docs: aside overflow behavior
  apps/dialtone-documentation/docs/.vuepress/theme/components/PageToc.vue
Labels: documentation, no-visual-test

#173 docs: fixed links on design section
  apps/dialtone-documentation/docs/design/size/index.md
  apps/dialtone-documentation/docs/design/space/index.md
Labels: documentation, no-visual-test

#160 feat(item-layout): add unstyled prop
  packages/dialtone-css/lib/build/less/components/item-layout.less
  packages/dialtone-vue2/components/item_layout/item_layout.mdx
  packages/dialtone-vue2/components/item_layout/item_layout.stories.js
  packages/dialtone-vue2/components/item_layout/item_layout.vue
  packages/dialtone-vue2/components/item_layout/item_layout_default.story.vue
  packages/dialtone-vue2/recipes/leftbar/callbox/callbox_variants.story.vue
  packages/dialtone-vue3/components/item_layout/item_layout.mdx
  packages/dialtone-vue3/components/item_layout/item_layout.stories.js
  packages/dialtone-vue3/components/item_layout/item_layout.vue
  packages/dialtone-vue3/components/item_layout/item_layout_default.story.vue
Labels: visual-test-ready

#168 fix(contact-info): use item layout instead of list item
  packages/dialtone-vue2/index.js
  packages/dialtone-vue2/recipes/item_layout/contact_info/contact_info.mdx
  packages/dialtone-vue2/recipes/item_layout/contact_info/contact_info.stories.js
  packages/dialtone-vue2/recipes/item_layout/contact_info/contact_info.test.js
  packages/dialtone-vue2/recipes/item_layout/contact_info/contact_info.vue
  packages/dialtone-vue2/recipes/item_layout/contact_info/contact_info_default.story.vue
  packages/dialtone-vue2/recipes/item_layout/contact_info/contact_info_variants.story.vue
  packages/dialtone-vue2/recipes/item_layout/contact_info/index.js
  packages/dialtone-vue3/index.js
  packages/dialtone-vue3/recipes/item_layout/contact_info/contact_info.mdx
  packages/dialtone-vue3/recipes/item_layout/contact_info/contact_info.stories.js
  packages/dialtone-vue3/recipes/item_layout/contact_info/contact_info.test.js
  packages/dialtone-vue3/recipes/item_layout/contact_info/contact_info.vue
  packages/dialtone-vue3/recipes/item_layout/contact_info/contact_info_default.story.vue
  packages/dialtone-vue3/recipes/item_layout/contact_info/contact_info_variants.story.vue
  packages/dialtone-vue3/recipes/item_layout/contact_info/index.js
  percy.base_config.cjs
Labels: visual-test-ready

#174 feat(message-input): add mentions to message input
  packages/dialtone-icons/src/keywords.json
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.stories.js
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.vue
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input_default.story.vue
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.stories.js
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.vue
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input_default.story.vue
Labels: no-visual-test

#172 fix(popover): remove data-popper-escaped
  packages/dialtone-vue2/components/popover/popover.vue
  packages/dialtone-vue2/components/tooltip/tooltip.vue
  packages/dialtone-vue3/components/popover/popover.vue
  packages/dialtone-vue3/components/tooltip/tooltip.vue
Labels: no-visual-test

#170 docs: use CodeExampleTabs component for avatar page
  apps/dialtone-documentation/docs/.vuepress/baseComponents/CodeExampleTabs.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/CopyButton.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/ExampleTabs.vue
  apps/dialtone-documentation/docs/.vuepress/client.js
  apps/dialtone-documentation/docs/components/avatar.md
  packages/dialtone-vue2/components/tabs/tab_group.vue
  packages/dialtone-vue3/components/tabs/tab_group.vue
Labels: no-visual-test

#175 chore: fix yeoman generator
  generator-dialtone/generators/vue2/index.js
  generator-dialtone/generators/vue2/templates/component.ejs
  generator-dialtone/generators/vue2/templates/constants.ejs
  generator-dialtone/generators/vue2/templates/index.ejs
  generator-dialtone/generators/vue2/templates/mdx.ejs
  generator-dialtone/generators/vue2/templates/stories.ejs
  generator-dialtone/generators/vue2/templates/story.ejs
  generator-dialtone/generators/vue2/templates/test.ejs
  generator-dialtone/generators/vue3/index.js
  generator-dialtone/generators/vue3/templates/component.ejs
  generator-dialtone/generators/vue3/templates/constants.ejs
  generator-dialtone/generators/vue3/templates/index.ejs
  generator-dialtone/generators/vue3/templates/mdx.ejs
  generator-dialtone/generators/vue3/templates/stories.ejs
  generator-dialtone/generators/vue3/templates/story.ejs
  generator-dialtone/generators/vue3/templates/test.ejs
  generator-dialtone/package.json
  package.json
  packages/dialtone-vue2/.github/TEST_CONTRIBUTING/TEST_GUIDELINE.md
  packages/dialtone-vue2/generator-dialtone-vue/generators/app/templates/test.ejs
  packages/dialtone-vue2/package.json
  packages/dialtone-vue3/.github/CONTRIBUTING.md
  packages/dialtone-vue3/.github/TEST_CONTRIBUTING/TEST_GUIDELINE.md
  packages/dialtone-vue3/generator-dialtone-vue/generators/app/index.js
  packages/dialtone-vue3/generator-dialtone-vue/generators/app/templates/test.ejs
  packages/dialtone-vue3/generator-dialtone-vue/package.json
  packages/dialtone-vue3/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: no-visual-test

#182 fix(message-input): color contrast on cancel button
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.vue
  packages/dialtone-vue3/recipes/conversation_view/message_input/message_input.vue
Labels: visual-test-ready

#183 fix(feed-item-row): accessibility error
  packages/dialtone-vue2/components/list_item/list_item.test.js
  packages/dialtone-vue2/components/list_item/list_item.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row.stories.js
  packages/dialtone-vue3/components/list_item/list_item.test.js
  packages/dialtone-vue3/components/list_item/list_item.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row.stories.js
Labels: no-visual-test
