Repository dialpad/dialtone, pull requests merged in 2025-08, with the labels that each got.

#839 feat(icon): DLT-2619 deprecate ai notes
  apps/dialtone-documentation/docs/.vuepress/views/IconCatalog.vue
  packages/dialtone-icons/src/keywords-icons.json
Labels: no-visual-test

#849 fix(tab): DP-148500 tabs not loading instantly
  packages/dialtone-vue2/components/tab/tab_group.vue
  packages/dialtone-vue3/components/tab/tab_group.vue
Labels: no-visual-test

#862 feat(utilities): DLT-2115 d-d-contents
  apps/dialtone-documentation/docs/_data/display.json
  apps/dialtone-documentation/docs/utilities/layout/display.md
  packages/dialtone-css/lib/build/less/utilities/layout.less
Labels: visual-test-ready

#822 feat(color): DLT-2571 added chart design tokens
  packages/dialtone-tokens/build-sd-transforms.js
  packages/dialtone-tokens/tokens/semantic/dp/dark.json
  packages/dialtone-tokens/tokens/semantic/dp/default.json
Labels: no-visual-test, skip-bundle-size-check

#840 feat(color): DLT-2594 shell design tokens
  packages/dialtone-tokens/tokens/$metadata.json
  packages/dialtone-tokens/tokens/$themes.json
  packages/dialtone-tokens/tokens/base/dark.json
  packages/dialtone-tokens/tokens/components/presence/dark.json
  packages/dialtone-tokens/tokens/components/presence/default.json
  packages/dialtone-tokens/tokens/semantic/cox/dark.json
  packages/dialtone-tokens/tokens/semantic/cox/default.json
  packages/dialtone-tokens/tokens/semantic/tmo/dark.json
  packages/dialtone-tokens/tokens/semantic/tmo/default.json
  packages/dialtone-tokens/tokens/theme/aegean/dark.json
  packages/dialtone-tokens/tokens/theme/aegean/default.json
  packages/dialtone-tokens/tokens/theme/botany/dark.json
  packages/dialtone-tokens/tokens/theme/botany/default.json
  packages/dialtone-tokens/tokens/theme/buttercream/dark.json
  packages/dialtone-tokens/tokens/theme/buttercream/default.json
  packages/dialtone-tokens/tokens/theme/ceruleo/dark.json
  packages/dialtone-tokens/tokens/theme/ceruleo/default.json
  packages/dialtone-tokens/tokens/theme/deca/dark.json
  packages/dialtone-tokens/tokens/theme/deca/default.json
  packages/dialtone-tokens/tokens/theme/dp/dark.json
  packages/dialtone-tokens/tokens/theme/dp/default.json
  packages/dialtone-tokens/tokens/theme/expressive/default.json
  packages/dialtone-tokens/tokens/theme/expressive/sm.json
  packages/dialtone-tokens/tokens/theme/high-desert/dark.json
  packages/dialtone-tokens/tokens/theme/high-desert/default.json
  packages/dialtone-tokens/tokens/theme/melon/dark.json
  packages/dialtone-tokens/tokens/theme/melon/default.json
  packages/dialtone-tokens/tokens/theme/plum/dark.json
  packages/dialtone-tokens/tokens/theme/plum/default.json
  packages/dialtone-tokens/tokens/theme/sunflower/dark.json
  packages/dialtone-tokens/tokens/theme/sunflower/default.json
  packages/dialtone-tokens/tokens/theme/tmo/dark.json
  packages/dialtone-tokens/tokens/theme/tmo/default.json
  packages/dialtone-tokens/tokens/theme/verdant-haze/dark.json
  packages/dialtone-tokens/tokens/theme/verdant-haze/default.json
Labels: visual-test-ready, skip-bundle-size-check

#860 fix(rich-text-editor): DLT-2690 custom emojis not working
  packages/dialtone-vue2/common/custom-emoji.json
  packages/dialtone-vue2/common/custom-emoji.test.js
  packages/dialtone-vue2/common/emoji.test.js
  packages/dialtone-vue2/common/emoji/index.js
  packages/dialtone-vue2/components/emoji/emoji.test.js
  packages/dialtone-vue2/components/emoji_picker/emoji_picker.stories.js
  packages/dialtone-vue2/components/emoji_text_wrapper/emoji_text_wrapper.test.js
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/EmojiComponent.vue
  packages/dialtone-vue2/components/rich_text_editor/extensions/emoji/emoji.js
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.stories.js
  packages/dialtone-vue2/recipes/conversation_view/message_input/message_input.vue
Labels: no-visual-test

#864 feat(utilities): DLT-2396 word-break: break-word and word-wrap: anywhere
  apps/dialtone-documentation/docs/.vuepress/common/utilities.js
  apps/dialtone-documentation/docs/utilities/backgrounds/color.md
  apps/dialtone-documentation/docs/utilities/borders/color.md
  apps/dialtone-documentation/docs/utilities/borders/divide-color.md
  apps/dialtone-documentation/docs/utilities/typography/font-color.md
  apps/dialtone-documentation/docs/utilities/typography/word-break.md
  apps/dialtone-documentation/docs/utilities/typography/word-wrap.md
  packages/dialtone-css/lib/build/less/utilities/typography.less
Labels: visual-test-ready

#869 fix(tokens): DLT-2712 remove prepended color from inputs, action, theme groups
  packages/dialtone-tokens/tokens/theme/dp/dark.json
  packages/dialtone-tokens/tokens/theme/dp/default.json
Labels: visual-test-ready

#875 fix(combobox-multi-select): NO-JIRA prevent losing focus on input
  packages/dialtone-vue2/components/chip/chip.test.js
  packages/dialtone-vue2/components/chip/chip.vue
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.test.js
  packages/dialtone-vue2/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
  packages/dialtone-vue3/components/chip/chip.test.js
  packages/dialtone-vue3/components/chip/chip.vue
  packages/dialtone-vue3/recipes/comboboxes/combobox_multi_select/combobox_multi_select.test.js
  packages/dialtone-vue3/recipes/comboboxes/combobox_multi_select/combobox_multi_select.vue
Labels: no-visual-test

#874 feat(css-utility): DLT-2715 add default color for border css utilities
  apps/dialtone-documentation/docs/.vuepress/baseComponents/BlogPostPreview.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/ComponentAccessibleTable.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/ComponentClassTable.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/ComponentVueApiTable.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/DesignColorTable.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/IconPopoverContent.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/NewUtilityClassTable.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/ThemeColorTable.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/UtilityClassTable.vue
  apps/dialtone-documentation/docs/.vuepress/baseComponents/tokens/TokenTable.vue
  apps/dialtone-documentation/docs/.vuepress/theme/components/MobileSidebar.vue
  apps/dialtone-documentation/docs/about/whats-new/posts/2024-3-20.md
  apps/dialtone-documentation/docs/about/whats-new/posts/2024-4-15.md
  apps/dialtone-documentation/docs/components/datepicker.md
  apps/dialtone-documentation/docs/components/icon.md
  apps/dialtone-documentation/docs/components/scrollbar.md
  apps/dialtone-documentation/docs/components/stack.md
  apps/dialtone-documentation/docs/design/size/index.md
  apps/dialtone-documentation/docs/design/space/index.md
  apps/dialtone-documentation/docs/design/typography/index.md
  apps/dialtone-documentation/docs/utilities/backgrounds/clip.md
  apps/dialtone-documentation/docs/utilities/backgrounds/patterns.md
  apps/dialtone-documentation/docs/utilities/borders/color.md
  apps/dialtone-documentation/docs/utilities/borders/direction.md
  apps/dialtone-documentation/docs/utilities/borders/divide-width.md
  apps/dialtone-documentation/docs/utilities/borders/radius.md
  apps/dialtone-documentation/docs/utilities/borders/style.md
  apps/dialtone-documentation/docs/utilities/borders/width.md
  apps/dialtone-documentation/docs/utilities/flex/direction-wrap-flow.md
  apps/dialtone-documentation/docs/utilities/flex/flex-grow-shrink.md
  apps/dialtone-documentation/docs/utilities/interactivity/resize.md
  apps/dialtone-documentation/docs/utilities/layout/box-sizing.md
  apps/dialtone-documentation/docs/utilities/layout/display.md
  apps/dialtone-documentation/docs/utilities/layout/overflow.md
  apps/dialtone-documentation/docs/utilities/layout/z-index.md
  apps/dialtone-documentation/docs/utilities/responsive/breakpoints.md
  apps/dialtone-documentation/docs/utilities/sizing/height.md
  apps/dialtone-documentation/docs/utilities/sizing/max-height.md
  apps/dialtone-documentation/docs/utilities/sizing/max-width.md
  apps/dialtone-documentation/docs/utilities/sizing/min-height.md
  apps/dialtone-documentation/docs/utilities/sizing/min-width.md
  apps/dialtone-documentation/docs/utilities/sizing/width.md
  apps/dialtone-documentation/docs/utilities/spacing/auto-spacing.md
  apps/dialtone-documentation/docs/utilities/typography/font-family.md
  apps/dialtone-documentation/docs/utilities/typography/font-size.md
  apps/dialtone-documentation/docs/utilities/typography/font-weight.md
  apps/dialtone-documentation/docs/utilities/typography/line-height.md
  packages/dialtone-css/lib/build/less/utilities/borders.less
  packages/dialtone-vue2/components/loader/loader_variants.story.vue
  packages/dialtone-vue2/components/split_button/split_button_variants.story.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
  packages/dialtone-vue2/recipes/conversation_view/feed_item_row/feed_item_row_variants.story.vue
  packages/dialtone-vue3/components/loader/loader_variants.story.vue
  packages/dialtone-vue3/components/split_button/split_button_variants.story.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row_default.story.vue
  packages/dialtone-vue3/recipes/conversation_view/feed_item_row/feed_item_row_variants.story.vue
Labels: visual-test-ready

#881 fix(docs): DLT-2716 add chart-colors to design colors extraction path
  apps/dialtone-documentation/docs/.vuepress/theme/index.js
Labels: no-visual-test

#890 chore: NO-JIRA temporarily suppress theme list
  apps/dialtone-documentation/docs/design/colors/themes/index.md
Labels: no-visual-test
